# Generated by Django 5.2.6 on 2025-12-18 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Telefone')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Login_Usuario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Email')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Nome de Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('ACE', 'Aceito'), ('REC', 'Recusado'), ('AND', 'Em andamento'), ('CON', 'Concluído')], default='PEN', max_length=3, verbose_name='Status do Pedido')),
                ('tipo', models.CharField(choices=[('CON', 'Console'), ('CTR', 'Controle'), ('OUT', 'Outros')], default='CON', max_length=3, verbose_name='Tipo de Pedido')),
                ('data_de_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('detalhes_orcamento', models.TextField(verbose_name='Detalhes do Orçamento')),
                ('valor_orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Orçamento')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente')),
            ],
            options={
                'ordering': ['-data_de_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('SUCESSO', 'Sucesso'), ('ALERTA', 'Alerta'), ('ERRO', 'Erro')], default='INFO', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedidos', verbose_name='Pedido')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
