# Generated by Django 5.2.6 on 2025-12-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_cliente_login_usuario_controles_consoles_outros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controles',
            name='detalhes_orcamento',
        ),
        migrations.RemoveField(
            model_name='outros',
            name='detalhes_orcamento',
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CON', 'Console'), ('OUT', 'Acessórios/Outros')], default='CON', max_length=3, verbose_name='Tipo de Pedido')),
                ('data_de_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('detalhes_orcamento', models.TextField(verbose_name='Detalhes do Orçamento')),
                ('valor_orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Orçamento')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Consoles',
        ),
        migrations.DeleteModel(
            name='Controles',
        ),
        migrations.DeleteModel(
            name='Outros',
        ),
    ]
