# Generated by Django 5.2.6 on 2025-12-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_controles_detalhes_orcamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'ordering': ['-data_de_entrada']},
        ),
    ]
