# Generated by Django 5.2.6 on 2025-12-10 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_pedidos_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('ACE', 'Aceito'), ('REC', 'Recusado'), ('AND', 'Em andamento'), ('CON', 'Concluído')], default='PEN', max_length=3, verbose_name='Status do Pedido'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('SUCESSO', 'Sucesso'), ('ALERTA', 'Alerta'), ('ERRO', 'Erro')], default='INFO', max_length=20)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedidos', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
