#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python workapp/manage.py migrate

python workapp/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn workapp.main.wsgi --bind 0.0.0.0:5000 --chdir=/app/workapp