# Generated by Django 5.2.6 on 2025-10-10 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarioadaptado_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Usuario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Email')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Nome de Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Controles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=150, verbose_name='Nome do cliente')),
                ('tipo_controle', models.CharField(max_length=100, verbose_name='Tipo de Controle')),
                ('data_de_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('valor_orcamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Orçamento')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('detalhes_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.login_usuario', verbose_name='Detalhes do Orçamento')),
            ],
        ),
        migrations.CreateModel(
            name='Consoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=150, verbose_name='Nome do cliente')),
                ('tipo_console', models.CharField(max_length=100, verbose_name='Tipo de Console')),
                ('data_de_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('valor_orcamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Orçamento')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('detalhes_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.login_usuario', verbose_name='Detalhes do Orçamento')),
            ],
        ),
        migrations.CreateModel(
            name='Outros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=150, verbose_name='Nome do cliente')),
                ('tipo_outro', models.CharField(max_length=100, verbose_name='Acessórios/Outros')),
                ('data_de_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('valor_orcamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Orçamento')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('detalhes_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.login_usuario', verbose_name='Detalhes do Orçamento')),
            ],
        ),
        migrations.DeleteModel(
            name='UsuarioAdaptado',
        ),
    ]
